SELECT TOP 1000 [id_incidencia]
      ,[usr]
      ,[id_pc]
      ,[data]
      ,[hora]
      ,[problema]
      ,[id_prioritat]
      ,[estat]
      ,[solucio]
      ,[darrera_ullada]
      ,[darrera_ullada_hora]
      ,[id_cat]
      ,[id_estat]
  FROM [CATMANAGER].[dbo].[incidencies]